[dependencies.icentral-deps]
path = "../icentral-deps"
[dependencies.icentral-bcc]
path = "../icentral-bcc"
[dependencies.icentral-brandes]
path = "../icentral-brandes"
[dependencies.icentral-edge]
path = "../icentral-edge"
[dependencies.icentral-edges]
path = "../icentral-edges"
[dependencies.icentral-errors]
path = "../icentral-errors"
[dependencies.icentral-gen-rand-edges]
path = "../icentral-gen-rand-edges"
[dependencies.icentral-graph]
path = "../icentral-graph"
[dependencies.icentral-graph-hash]
path = "../icentral-graph-hash"
[dependencies.icentral-graph-interface]
path = "../icentral-graph-interface"
[dependencies.icentral-muc]
path = "../icentral-muc"
[dependencies.icentral-mucid]
path = "../icentral-mucid"
[dependencies.icentral-neighbors]
path = "../icentral-neighbors"
[dependencies.icentral-nodeid]
path = "../icentral-nodeid"
[dependencies.icentral-scores]
path = "../icentral-scores"
[dependencies.icentral-stats]
path = "../icentral-stats"
[dependencies.icentral-timer]
path = "../icentral-timer"
[dependencies]
renew-traits = "0.1.0"
[package]
edition = "2021"
name = "icentral-test-qube"
version = "0.1.0"
