[dependencies.icentral-deps]
path = "../icentral-deps"
[dependencies.icentral-mindexed-map]
path = "../icentral-mindexed-map"
[dependencies.icentral-nodeid]
path = "../icentral-nodeid"
[package]
edition = "2021"
name = "icentral-visit-markers"
version = "0.1.0"
