[dependencies.icentral-deps]
path = "../icentral-deps"
[dependencies.icentral-cycle]
path = "../icentral-cycle"
[dependencies.icentral-edge]
path = "../icentral-edge"
[dependencies.icentral-edges]
path = "../icentral-edges"
[dependencies.icentral-errors]
path = "../icentral-errors"
[dependencies.icentral-graph-interface]
path = "../icentral-graph-interface"
[dependencies.icentral-muc]
path = "../icentral-muc"
[dependencies.icentral-nodeid]
path = "../icentral-nodeid"
[package]
edition = "2021"
name = "icentral-qube"
version = "0.1.0"
