[dependencies.icentral-deps]
path = "../icentral-deps"
[dependencies.icentral-component]
path = "../icentral-component"
[dependencies.icentral-edge]
path = "../icentral-edge"
[dependencies.icentral-errors]
path = "../icentral-errors"
[dependencies.icentral-node-queue]
path = "../icentral-node-queue"
[dependencies.icentral-nodeid]
path = "../icentral-nodeid"
[dependencies.icentral-sigmas]
path = "../icentral-sigmas"
[dependencies.icentral-workspace]
path = "../icentral-workspace"
[dependencies.renew-traits]
path = "../renew-traits"
[package]
edition = "2021"
name = "icentral-partial-bbfs"
version = "0.1.0"
